FROM ubuntu

RUN apt update
RUN apt install -y wget net-tools bzip2 locales
RUN locale-gen en_US.UTF-8
RUN apt install -y ttf-wqy-zenhei
RUN apt install -y vnc4server
RUN apt install -y xfce4 xfce4-terminal